export const CHANGE_SEND_BUTTON = 'CHANGE_SEND_BUTTON';

export const REGISTER_AMOUNT = 'REGISTER_AMOUNT';

export const REGISTER_MESSAGE = 'REGISTER_MESSAGE';

export const UPDATE_CONFIG_DATA = 'UPDATE_CONFIG_DATA';
