export const CHANGE_SEND_BUTTON = 'CHANGE_SEND_BUTTON';

export const REGISTER_DEFAULT_AMOUNT = 'REGISTER_DEFAULT_AMOUNT';

export const REGISTER_DEFAULT_MESSAGE = 'REGISTER_DEFAULT_MESSAGE';

export const UPDATE_CONFIG_DATA = 'UPDATE_CONFIG_DATA';
